### ISSUE TITLE
How to cite CO2System.jl

### ISSUE THREAD

**Issue by lqjiang** [mvdh7/CO2System.jl#2]
I'm trying to cite this tool in a peer-reviewed publication and wonder if you could help me create a citation for this Julia version of the CO2SYS, i.e., CO2System.jl?

Below is the citation info for this tool according to this Github page. Unfortunately, none of them are specific to the CO2System.jl. Are there any plans to min a citation using Zenodo? 

**CITATION**

If you use any CO2SYS related software, please cite the original work by Lewis and Wallace (1998).
If you use CO2SYS.m, please cite van Heuven et al (2011).
If you use errors.m or derivnum.m, please cite Orr et al. (2018).

**Comment by mvdh7** [comment]
Hey, thanks for asking and sorry for the delay!
Just added the current version to Zenodo: https://doi.org/10.5281/zenodo.6395674

**Comment by lqjiang** [comment]
Many thanks, Matthew!
